// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ban.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createBan = `-- name: CreateBan :one
INSERT INTO bans (
	user_id
) VALUES(
	$1
) RETURNING id, user_id, created_at
`

func (q *Queries) CreateBan(ctx context.Context, userID uuid.UUID) (Ban, error) {
	row := q.db.QueryRow(ctx, createBan, userID)
	var i Ban
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const deleteBan = `-- name: DeleteBan :exec
DELETE FROM bans WHERE id = $1
`

func (q *Queries) DeleteBan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBan, id)
	return err
}

const getBanForUser = `-- name: GetBanForUser :one
SELECT id, user_id, created_at FROM bans
WHERE user_id = $1
`

func (q *Queries) GetBanForUser(ctx context.Context, userID uuid.UUID) (Ban, error) {
	row := q.db.QueryRow(ctx, getBanForUser, userID)
	var i Ban
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}
