// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_method.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createDeliveryMethod = `-- name: CreateDeliveryMethod :one
INSERT INTO delivery_methods (
	description, price_cent, vendor_id
) VALUES (
	$1, $2, $3
) RETURNING id, vendor_id, description, price_cent, deleted_at
`

type CreateDeliveryMethodParams struct {
	Description string
	PriceCent   int64
	VendorID    uuid.UUID
}

func (q *Queries) CreateDeliveryMethod(ctx context.Context, arg CreateDeliveryMethodParams) (DeliveryMethod, error) {
	row := q.db.QueryRow(ctx, createDeliveryMethod, arg.Description, arg.PriceCent, arg.VendorID)
	var i DeliveryMethod
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Description,
		&i.PriceCent,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDeliveryMethod = `-- name: DeleteDeliveryMethod :exec
UPDATE delivery_methods 
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteDeliveryMethod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeliveryMethod, id)
	return err
}

const getAllDeliveryMethods = `-- name: GetAllDeliveryMethods :many
SELECT id, vendor_id, description, price_cent, deleted_at 
FROM delivery_methods
WHERE delivery_methods.deleted_at IS NULL
`

func (q *Queries) GetAllDeliveryMethods(ctx context.Context) ([]DeliveryMethod, error) {
	rows, err := q.db.Query(ctx, getAllDeliveryMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryMethod
	for rows.Next() {
		var i DeliveryMethod
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Description,
			&i.PriceCent,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveryMethod = `-- name: GetDeliveryMethod :one
SELECT id, vendor_id, description, price_cent, deleted_at 
FROM delivery_methods
WHERE id = $1
`

func (q *Queries) GetDeliveryMethod(ctx context.Context, id uuid.UUID) (DeliveryMethod, error) {
	row := q.db.QueryRow(ctx, getDeliveryMethod, id)
	var i DeliveryMethod
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Description,
		&i.PriceCent,
		&i.DeletedAt,
	)
	return i, err
}

const getDeliveryMethodForOrder = `-- name: GetDeliveryMethodForOrder :one
SELECT delivery_methods.id, delivery_methods.vendor_id, delivery_methods.description, delivery_methods.price_cent, delivery_methods.deleted_at 
FROM delivery_methods
JOIN orders ON orders.delivery_method_id = delivery_methods.id
WHERE orders.id = $1
`

func (q *Queries) GetDeliveryMethodForOrder(ctx context.Context, id uuid.UUID) (DeliveryMethod, error) {
	row := q.db.QueryRow(ctx, getDeliveryMethodForOrder, id)
	var i DeliveryMethod
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Description,
		&i.PriceCent,
		&i.DeletedAt,
	)
	return i, err
}

const getDeliveryMethodsForProduct = `-- name: GetDeliveryMethodsForProduct :many
SELECT delivery_methods.id, delivery_methods.vendor_id, delivery_methods.description, delivery_methods.price_cent, delivery_methods.deleted_at 
FROM delivery_methods
JOIN products ON products.vendor_id = delivery_methods.vendor_id
WHERE products.id = $1 AND delivery_methods.deleted_at IS NULL
`

func (q *Queries) GetDeliveryMethodsForProduct(ctx context.Context, id uuid.UUID) ([]DeliveryMethod, error) {
	rows, err := q.db.Query(ctx, getDeliveryMethodsForProduct, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryMethod
	for rows.Next() {
		var i DeliveryMethod
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Description,
			&i.PriceCent,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveryMethodsForVendor = `-- name: GetDeliveryMethodsForVendor :many
SELECT id, vendor_id, description, price_cent, deleted_at 
FROM delivery_methods
WHERE delivery_methods.vendor_id = $1 AND delivery_methods.deleted_at IS NULL
`

func (q *Queries) GetDeliveryMethodsForVendor(ctx context.Context, vendorID uuid.UUID) ([]DeliveryMethod, error) {
	rows, err := q.db.Query(ctx, getDeliveryMethodsForVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryMethod
	for rows.Next() {
		var i DeliveryMethod
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Description,
			&i.PriceCent,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
