// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dispute.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createDisputeOffer = `-- name: CreateDisputeOffer :one
INSERT INTO dispute_offers (
	refund_factor, order_id
) SELECT $1, $2
FROM orders
WHERE orders.id = $2 AND orders.status = 'disputed'
RETURNING id, refund_factor, status, order_id, created_at
`

type CreateDisputeOfferParams struct {
	RefundFactor float64
	OrderID      uuid.UUID
}

func (q *Queries) CreateDisputeOffer(ctx context.Context, arg CreateDisputeOfferParams) (DisputeOffer, error) {
	row := q.db.QueryRow(ctx, createDisputeOffer, arg.RefundFactor, arg.OrderID)
	var i DisputeOffer
	err := row.Scan(
		&i.ID,
		&i.RefundFactor,
		&i.Status,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const createDisputeOfferWithStatus = `-- name: CreateDisputeOfferWithStatus :one
INSERT INTO dispute_offers (
	refund_factor, order_id, status
) SELECT $1, $2, $3
FROM orders
WHERE orders.id = $2 AND orders.status = 'disputed'
RETURNING id, refund_factor, status, order_id, created_at
`

type CreateDisputeOfferWithStatusParams struct {
	RefundFactor float64
	OrderID      uuid.UUID
	Status       DisputeOfferStatus
}

func (q *Queries) CreateDisputeOfferWithStatus(ctx context.Context, arg CreateDisputeOfferWithStatusParams) (DisputeOffer, error) {
	row := q.db.QueryRow(ctx, createDisputeOfferWithStatus, arg.RefundFactor, arg.OrderID, arg.Status)
	var i DisputeOffer
	err := row.Scan(
		&i.ID,
		&i.RefundFactor,
		&i.Status,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getDisputeOffer = `-- name: GetDisputeOffer :one
SELECT id, refund_factor, status, order_id, created_at FROM dispute_offers
WHERE id = $1
`

func (q *Queries) GetDisputeOffer(ctx context.Context, id uuid.UUID) (DisputeOffer, error) {
	row := q.db.QueryRow(ctx, getDisputeOffer, id)
	var i DisputeOffer
	err := row.Scan(
		&i.ID,
		&i.RefundFactor,
		&i.Status,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getDisputeOffersForOrder = `-- name: GetDisputeOffersForOrder :many
SELECT id, refund_factor, status, order_id, created_at FROM dispute_offers
WHERE order_id = $1
`

func (q *Queries) GetDisputeOffersForOrder(ctx context.Context, orderID uuid.UUID) ([]DisputeOffer, error) {
	rows, err := q.db.Query(ctx, getDisputeOffersForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DisputeOffer
	for rows.Next() {
		var i DisputeOffer
		if err := rows.Scan(
			&i.ID,
			&i.RefundFactor,
			&i.Status,
			&i.OrderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisputeOfferStatus = `-- name: UpdateDisputeOfferStatus :one
UPDATE dispute_offers
SET status = $2
WHERE id = $1
RETURNING id, refund_factor, status, order_id, created_at
`

type UpdateDisputeOfferStatusParams struct {
	ID     uuid.UUID
	Status DisputeOfferStatus
}

func (q *Queries) UpdateDisputeOfferStatus(ctx context.Context, arg UpdateDisputeOfferStatusParams) (DisputeOffer, error) {
	row := q.db.QueryRow(ctx, updateDisputeOfferStatus, arg.ID, arg.Status)
	var i DisputeOffer
	err := row.Scan(
		&i.ID,
		&i.RefundFactor,
		&i.Status,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}
