// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rate.sql

package repo

import (
	"context"
)

const getExchangeRates = `-- name: GetExchangeRates :one
SELECT id, data, updated_at FROM exchange_rates WHERE id = 1
`

func (q *Queries) GetExchangeRates(ctx context.Context) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getExchangeRates)
	var i ExchangeRate
	err := row.Scan(&i.ID, &i.Data, &i.UpdatedAt)
	return i, err
}

const updateExchangeRates = `-- name: UpdateExchangeRates :exec
INSERT INTO exchange_rates (id, data)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE
SET data = EXCLUDED.data, 
	updated_at = NOW()
`

func (q *Queries) UpdateExchangeRates(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateExchangeRates, data)
	return err
}
