// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DisputeOfferStatus string

const (
	DisputeOfferStatusPending  DisputeOfferStatus = "pending"
	DisputeOfferStatusDeclined DisputeOfferStatus = "declined"
	DisputeOfferStatusAccepted DisputeOfferStatus = "accepted"
	DisputeOfferStatusForced   DisputeOfferStatus = "forced"
)

func (e *DisputeOfferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisputeOfferStatus(s)
	case string:
		*e = DisputeOfferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DisputeOfferStatus: %T", src)
	}
	return nil
}

type NullDisputeOfferStatus struct {
	DisputeOfferStatus DisputeOfferStatus
	Valid              bool // Valid is true if DisputeOfferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisputeOfferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DisputeOfferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisputeOfferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisputeOfferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisputeOfferStatus), nil
}

type InvoiceStatus string

const (
	InvoiceStatusPending   InvoiceStatus = "pending"
	InvoiceStatusConfirmed InvoiceStatus = "confirmed"
	InvoiceStatusExpired   InvoiceStatus = "expired"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus
	Valid         bool // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusPaid       OrderStatus = "paid"
	OrderStatusCancelled  OrderStatus = "cancelled"
	OrderStatusAccepted   OrderStatus = "accepted"
	OrderStatusDeclined   OrderStatus = "declined"
	OrderStatusDispatched OrderStatus = "dispatched"
	OrderStatusFinalized  OrderStatus = "finalized"
	OrderStatusDisputed   OrderStatus = "disputed"
	OrderStatusSettled    OrderStatus = "settled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type WithdrawalStatus string

const (
	WithdrawalStatusPending    WithdrawalStatus = "pending"
	WithdrawalStatusProcessing WithdrawalStatus = "processing"
)

func (e *WithdrawalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WithdrawalStatus(s)
	case string:
		*e = WithdrawalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WithdrawalStatus: %T", src)
	}
	return nil
}

type NullWithdrawalStatus struct {
	WithdrawalStatus WithdrawalStatus
	Valid            bool // Valid is true if WithdrawalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWithdrawalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WithdrawalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WithdrawalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWithdrawalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WithdrawalStatus), nil
}

type Ban struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type CartItem struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	PriceID    uuid.UUID
	CreatedAt  time.Time
}

type Category struct {
	ID        uuid.UUID
	ParentID  pgtype.UUID
	Name      string
	CreatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type DeliveryMethod struct {
	ID          uuid.UUID
	VendorID    uuid.UUID
	Description string
	PriceCent   int64
	DeletedAt   pgtype.Timestamptz
}

type Deposit struct {
	ID                  uuid.UUID
	WalletID            uuid.UUID
	InvoiceID           uuid.UUID
	AmountDepositedPico pgtype.Numeric
}

type DisputeOffer struct {
	ID           uuid.UUID
	RefundFactor float64
	Status       DisputeOfferStatus
	OrderID      uuid.UUID
	CreatedAt    time.Time
}

type ExchangeRate struct {
	ID        int32
	Data      []byte
	UpdatedAt time.Time
}

type Invoice struct {
	ID                 uuid.UUID
	Address            string
	AmountPico         pgtype.Numeric
	Status             InvoiceStatus
	AmountUnlockedPico pgtype.Numeric
	Permanent          bool
	CreatedAt          time.Time
}

type Notification struct {
	ID        uuid.UUID
	Title     string
	Content   string
	IsSeen    bool
	UserID    uuid.UUID
	CreatedAt time.Time
}

type Order struct {
	ID               uuid.UUID
	Status           OrderStatus
	Details          string
	TotalPricePico   pgtype.Numeric
	DeliveryMethodID uuid.UUID
	VendorID         uuid.UUID
	TermsOfServiceID uuid.UUID
	CustomerID       uuid.UUID
	NumExtends       int32
	CreatedAt        time.Time
	PaidAt           time.Time
	AcceptedAt       time.Time
	DispatchedAt     time.Time
	FinalizedAt      time.Time
	DisputedAt       time.Time
}

type OrderChatMessage struct {
	ID        uuid.UUID
	Message   string
	AuthorID  uuid.UUID
	OrderID   uuid.UUID
	CreatedAt time.Time
}

type OrderInvoice struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	InvoiceID uuid.UUID
}

type OrderItem struct {
	ID      uuid.UUID
	OrderID uuid.UUID
	PriceID uuid.UUID
	Count   int32
}

type PriceTier struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	PriceCent int64
	DeletedAt pgtype.Timestamptz
}

type Product struct {
	ID          uuid.UUID
	Title       string
	Description string
	CategoryID  uuid.UUID
	Inventory   int32
	ShipsFrom   string
	ShipsTo     string
	VendorID    uuid.UUID
	DeletedAt   pgtype.Timestamptz
}

type ProductReview struct {
	ID          uuid.UUID
	Grade       int32
	Comment     string
	OrderItemID uuid.UUID
}

type Review struct {
	ID        uuid.UUID
	Grade     int32
	Comment   string
	OrderID   uuid.UUID
	CreatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type Setting struct {
	ID        int32
	Data      []byte
	UpdatedAt time.Time
}

type TermsOfService struct {
	ID        uuid.UUID
	Content   string
	VendorID  uuid.UUID
	CreatedAt time.Time
}

type Ticket struct {
	ID        uuid.UUID
	Subject   string
	Message   string
	AuthorID  uuid.UUID
	IsOpen    bool
	CreatedAt time.Time
}

type TicketResponse struct {
	ID         uuid.UUID
	Message    string
	TicketID   uuid.UUID
	AuthorName string
	CreatedAt  time.Time
}

type Transaction struct {
	ID        uuid.UUID
	Hash      string
	CreatedAt time.Time
}

type User struct {
	ID               uuid.UUID
	Username         string
	PasswordHash     string
	PgpKey           string
	PrevLogin        time.Time
	Locale           string
	Currency         string
	TwofaEnabled     bool
	IncognitoEnabled bool
	CreatedAt        time.Time
}

type VendorApplication struct {
	ID             uuid.UUID
	ExistingVendor bool
	Letter         string
	PricePaidPico  pgtype.Numeric
	UserID         uuid.UUID
	CreatedAt      time.Time
}

type VendorLicense struct {
	ID            uuid.UUID
	PricePaidPico pgtype.Numeric
	UserID        uuid.UUID
	CreatedAt     time.Time
}

type Wallet struct {
	ID          uuid.UUID
	BalancePico pgtype.Numeric
	UserID      uuid.UUID
}

type Withdrawal struct {
	ID                 uuid.UUID
	AmountPico         pgtype.Numeric
	DestinationAddress string
	Status             WithdrawalStatus
	CreatedAt          time.Time
}
