// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_chat.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createOrderChatMessage = `-- name: CreateOrderChatMessage :one
INSERT INTO order_chat_messages (
	message, author_id, order_id
) VALUES (
	$1, $2, $3
) RETURNING id, message, author_id, order_id, created_at
`

type CreateOrderChatMessageParams struct {
	Message  string
	AuthorID uuid.UUID
	OrderID  uuid.UUID
}

func (q *Queries) CreateOrderChatMessage(ctx context.Context, arg CreateOrderChatMessageParams) (OrderChatMessage, error) {
	row := q.db.QueryRow(ctx, createOrderChatMessage, arg.Message, arg.AuthorID, arg.OrderID)
	var i OrderChatMessage
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.AuthorID,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderChatMessagesForOrder = `-- name: GetOrderChatMessagesForOrder :many
SELECT id, message, author_id, order_id, created_at FROM order_chat_messages
WHERE order_id = $1
`

func (q *Queries) GetOrderChatMessagesForOrder(ctx context.Context, orderID uuid.UUID) ([]OrderChatMessage, error) {
	rows, err := q.db.Query(ctx, getOrderChatMessagesForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderChatMessage
	for rows.Next() {
		var i OrderChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.AuthorID,
			&i.OrderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderChatMessagesForOrderJoinAuthor = `-- name: GetOrderChatMessagesForOrderJoinAuthor :many
SELECT chat.id, chat.message, chat.author_id, chat.order_id, chat.created_at, users.id, users.username, users.password_hash, users.pgp_key, users.prev_login, users.locale, users.currency, users.twofa_enabled, users.incognito_enabled, users.created_at
FROM order_chat_messages AS chat
JOIN users ON users.id = chat.author_id
WHERE chat.order_id = $1
ORDER BY chat.created_at ASC
`

type GetOrderChatMessagesForOrderJoinAuthorRow struct {
	OrderChatMessage OrderChatMessage
	User             User
}

func (q *Queries) GetOrderChatMessagesForOrderJoinAuthor(ctx context.Context, orderID uuid.UUID) ([]GetOrderChatMessagesForOrderJoinAuthorRow, error) {
	rows, err := q.db.Query(ctx, getOrderChatMessagesForOrderJoinAuthor, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderChatMessagesForOrderJoinAuthorRow
	for rows.Next() {
		var i GetOrderChatMessagesForOrderJoinAuthorRow
		if err := rows.Scan(
			&i.OrderChatMessage.ID,
			&i.OrderChatMessage.Message,
			&i.OrderChatMessage.AuthorID,
			&i.OrderChatMessage.OrderID,
			&i.OrderChatMessage.CreatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.PasswordHash,
			&i.User.PgpKey,
			&i.User.PrevLogin,
			&i.User.Locale,
			&i.User.Currency,
			&i.User.TwofaEnabled,
			&i.User.IncognitoEnabled,
			&i.User.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
