// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
	title, description, category_id, inventory, ships_from, ships_to, vendor_id
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
) RETURNING id, title, description, category_id, inventory, ships_from, ships_to, vendor_id, deleted_at
`

type CreateProductParams struct {
	Title       string
	Description string
	CategoryID  uuid.UUID
	Inventory   int32
	ShipsFrom   string
	ShipsTo     string
	VendorID    uuid.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.Inventory,
		arg.ShipsFrom,
		arg.ShipsTo,
		arg.VendorID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.Inventory,
		&i.ShipsFrom,
		&i.ShipsTo,
		&i.VendorID,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, title, description, category_id, inventory, ships_from, ships_to, vendor_id, deleted_at FROM products
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.Inventory,
		&i.ShipsFrom,
		&i.ShipsTo,
		&i.VendorID,
		&i.DeletedAt,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, title, description, category_id, inventory, ships_from, ships_to, vendor_id, deleted_at FROM products
WHERE deleted_at IS NULL
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.Inventory,
			&i.ShipsFrom,
			&i.ShipsTo,
			&i.VendorID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForVendor = `-- name: GetProductsForVendor :many
SELECT id, title, description, category_id, inventory, ships_from, ships_to, vendor_id, deleted_at FROM products
WHERE vendor_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductsForVendor(ctx context.Context, vendorID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsForVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.Inventory,
			&i.ShipsFrom,
			&i.ShipsTo,
			&i.VendorID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduceProductInventory = `-- name: ReduceProductInventory :exec
UPDATE products
SET inventory = inventory - $2::int
WHERE id = $1 AND inventory >= $2::int AND $2::int >= 0
`

type ReduceProductInventoryParams struct {
	ID     uuid.UUID
	Amount int32
}

func (q *Queries) ReduceProductInventory(ctx context.Context, arg ReduceProductInventoryParams) error {
	_, err := q.db.Exec(ctx, reduceProductInventory, arg.ID, arg.Amount)
	return err
}

const updateProductInventory = `-- name: UpdateProductInventory :exec
UPDATE products
SET inventory = $2
WHERE id = $1
`

type UpdateProductInventoryParams struct {
	ID        uuid.UUID
	Inventory int32
}

func (q *Queries) UpdateProductInventory(ctx context.Context, arg UpdateProductInventoryParams) error {
	_, err := q.db.Exec(ctx, updateProductInventory, arg.ID, arg.Inventory)
	return err
}
