// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package repo

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT data FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings
SET data = $1, updated_at = NOW()
WHERE id = 1
`

func (q *Queries) UpdateSettings(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateSettings, data)
	return err
}
