// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticket.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const closeTicket = `-- name: CloseTicket :one
UPDATE tickets
SET is_open = false
WHERE id = $1
RETURNING id, subject, message, author_id, is_open, created_at
`

func (q *Queries) CloseTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, closeTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Message,
		&i.AuthorID,
		&i.IsOpen,
		&i.CreatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
	subject, message, author_id
) VALUES(
	$1, $2, $3
) RETURNING id, subject, message, author_id, is_open, created_at
`

type CreateTicketParams struct {
	Subject  string
	Message  string
	AuthorID uuid.UUID
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.Subject, arg.Message, arg.AuthorID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Message,
		&i.AuthorID,
		&i.IsOpen,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenTickets = `-- name: GetOpenTickets :many
SELECT id, subject, message, author_id, is_open, created_at FROM tickets
WHERE is_open = true
`

func (q *Queries) GetOpenTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, getOpenTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Message,
			&i.AuthorID,
			&i.IsOpen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicket = `-- name: GetTicket :one
SELECT id, subject, message, author_id, is_open, created_at FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Message,
		&i.AuthorID,
		&i.IsOpen,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketsForAuthor = `-- name: GetTicketsForAuthor :many
SELECT id, subject, message, author_id, is_open, created_at FROM tickets
WHERE author_id = $1
`

func (q *Queries) GetTicketsForAuthor(ctx context.Context, authorID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, getTicketsForAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Message,
			&i.AuthorID,
			&i.IsOpen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
