// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticketresponse.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createTicketResponse = `-- name: CreateTicketResponse :one
INSERT INTO ticket_responses (
	message, ticket_id, author_name
) VALUES(
	$1, $2, $3
) RETURNING id, message, ticket_id, author_name, created_at
`

type CreateTicketResponseParams struct {
	Message    string
	TicketID   uuid.UUID
	AuthorName string
}

func (q *Queries) CreateTicketResponse(ctx context.Context, arg CreateTicketResponseParams) (TicketResponse, error) {
	row := q.db.QueryRow(ctx, createTicketResponse, arg.Message, arg.TicketID, arg.AuthorName)
	var i TicketResponse
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.TicketID,
		&i.AuthorName,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketResponsesForTicket = `-- name: GetTicketResponsesForTicket :many
SELECT id, message, ticket_id, author_name, created_at FROM ticket_responses
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetTicketResponsesForTicket(ctx context.Context, ticketID uuid.UUID) ([]TicketResponse, error) {
	rows, err := q.db.Query(ctx, getTicketResponsesForTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketResponse
	for rows.Next() {
		var i TicketResponse
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.TicketID,
			&i.AuthorName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
