// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
	hash
) VALUES (
	$1
) RETURNING id, hash, created_at
`

func (q *Queries) CreateTransaction(ctx context.Context, hash string) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, hash)
	var i Transaction
	err := row.Scan(&i.ID, &i.Hash, &i.CreatedAt)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, hash, created_at FROM transactions
`

func (q *Queries) GetTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(&i.ID, &i.Hash, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsBefore = `-- name: GetTransactionsBefore :many
SELECT id, hash, created_at FROM transactions
WHERE created_at < $1
`

func (q *Queries) GetTransactionsBefore(ctx context.Context, t time.Time) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsBefore, t)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(&i.ID, &i.Hash, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
