// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	username, password_hash, pgp_key
) VALUES (
	$1, $2, $3
) RETURNING id, username, password_hash, pgp_key, prev_login, locale, currency, twofa_enabled, incognito_enabled, created_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	PgpKey       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.PgpKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PgpKey,
		&i.PrevLogin,
		&i.Locale,
		&i.Currency,
		&i.TwofaEnabled,
		&i.IncognitoEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getNumberOfUsers = `-- name: GetNumberOfUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) GetNumberOfUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNumberOfUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, pgp_key, prev_login, locale, currency, twofa_enabled, incognito_enabled, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PgpKey,
		&i.PrevLogin,
		&i.Locale,
		&i.Currency,
		&i.TwofaEnabled,
		&i.IncognitoEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWithName = `-- name: GetUserWithName :one
SELECT id, username, password_hash, pgp_key, prev_login, locale, currency, twofa_enabled, incognito_enabled, created_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserWithName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PgpKey,
		&i.PrevLogin,
		&i.Locale,
		&i.Currency,
		&i.TwofaEnabled,
		&i.IncognitoEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
UPDATE users 
SET password_hash = $3 
WHERE username = $1 AND password_hash = $2
RETURNING id, username, password_hash, pgp_key, prev_login, locale, currency, twofa_enabled, incognito_enabled, created_at
`

type UpdateUserPasswordHashParams struct {
	Username        string
	PasswordHash    string
	NewPasswordHash string
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordHash, arg.Username, arg.PasswordHash, arg.NewPasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PgpKey,
		&i.PrevLogin,
		&i.Locale,
		&i.Currency,
		&i.TwofaEnabled,
		&i.IncognitoEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPgpKey = `-- name: UpdateUserPgpKey :one
UPDATE users 
SET pgp_key = $2 
WHERE id = $1
RETURNING id, username, password_hash, pgp_key, prev_login, locale, currency, twofa_enabled, incognito_enabled, created_at
`

type UpdateUserPgpKeyParams struct {
	ID     uuid.UUID
	PgpKey string
}

func (q *Queries) UpdateUserPgpKey(ctx context.Context, arg UpdateUserPgpKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPgpKey, arg.ID, arg.PgpKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PgpKey,
		&i.PrevLogin,
		&i.Locale,
		&i.Currency,
		&i.TwofaEnabled,
		&i.IncognitoEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPrevLogin = `-- name: UpdateUserPrevLogin :one
UPDATE users 
SET prev_login = NOW() 
WHERE id = $1
RETURNING id, username, password_hash, pgp_key, prev_login, locale, currency, twofa_enabled, incognito_enabled, created_at
`

func (q *Queries) UpdateUserPrevLogin(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPrevLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PgpKey,
		&i.PrevLogin,
		&i.Locale,
		&i.Currency,
		&i.TwofaEnabled,
		&i.IncognitoEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :exec
UPDATE users
SET locale = $2, currency = $3, twofa_enabled = $4, incognito_enabled = $5
WHERE id = $1
RETURNING id, username, password_hash, pgp_key, prev_login, locale, currency, twofa_enabled, incognito_enabled, created_at
`

type UpdateUserSettingsParams struct {
	ID               uuid.UUID
	Locale           string
	Currency         string
	TwofaEnabled     bool
	IncognitoEnabled bool
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error {
	_, err := q.db.Exec(ctx, updateUserSettings,
		arg.ID,
		arg.Locale,
		arg.Currency,
		arg.TwofaEnabled,
		arg.IncognitoEnabled,
	)
	return err
}
