// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendor_license.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createVendorLicense = `-- name: CreateVendorLicense :one
INSERT INTO vendor_licenses (
	price_paid_pico, user_id
) VALUES (
	$1, $2
) RETURNING id, price_paid_pico, vendor_info, user_id, created_at
`

type CreateVendorLicenseParams struct {
	PricePaidPico int64
	UserID        uuid.UUID
}

func (q *Queries) CreateVendorLicense(ctx context.Context, arg CreateVendorLicenseParams) (VendorLicense, error) {
	row := q.db.QueryRow(ctx, createVendorLicense, arg.PricePaidPico, arg.UserID)
	var i VendorLicense
	err := row.Scan(
		&i.ID,
		&i.PricePaidPico,
		&i.VendorInfo,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getNumberOfVendorLicenses = `-- name: GetNumberOfVendorLicenses :one
SELECT COUNT(*) FROM vendor_licenses
`

func (q *Queries) GetNumberOfVendorLicenses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNumberOfVendorLicenses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVendorLicenseForUser = `-- name: GetVendorLicenseForUser :one
SELECT id, price_paid_pico, vendor_info, user_id, created_at FROM vendor_licenses
WHERE user_id = $1
`

func (q *Queries) GetVendorLicenseForUser(ctx context.Context, userID uuid.UUID) (VendorLicense, error) {
	row := q.db.QueryRow(ctx, getVendorLicenseForUser, userID)
	var i VendorLicense
	err := row.Scan(
		&i.ID,
		&i.PricePaidPico,
		&i.VendorInfo,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const hasVendorLicense = `-- name: HasVendorLicense :one
SELECT 1
FROM vendor_licenses
WHERE user_id = $1
`

func (q *Queries) HasVendorLicense(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, hasVendorLicense, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateVendorInfo = `-- name: UpdateVendorInfo :one
UPDATE vendor_licenses
SET vendor_info = $2
WHERE id = $1
RETURNING id, price_paid_pico, vendor_info, user_id, created_at
`

type UpdateVendorInfoParams struct {
	ID         uuid.UUID
	VendorInfo string
}

func (q *Queries) UpdateVendorInfo(ctx context.Context, arg UpdateVendorInfoParams) (VendorLicense, error) {
	row := q.db.QueryRow(ctx, updateVendorInfo, arg.ID, arg.VendorInfo)
	var i VendorLicense
	err := row.Scan(
		&i.ID,
		&i.PricePaidPico,
		&i.VendorInfo,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
