// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendor_license.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createTermsOfService = `-- name: CreateTermsOfService :one
INSERT INTO terms_of_services (
	content, vendor_id
) VALUES (
	$1, $2
) RETURNING id, content, vendor_id, created_at
`

type CreateTermsOfServiceParams struct {
	Content  string
	VendorID uuid.UUID
}

func (q *Queries) CreateTermsOfService(ctx context.Context, arg CreateTermsOfServiceParams) (TermsOfService, error) {
	row := q.db.QueryRow(ctx, createTermsOfService, arg.Content, arg.VendorID)
	var i TermsOfService
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.VendorID,
		&i.CreatedAt,
	)
	return i, err
}

const createVendorLicense = `-- name: CreateVendorLicense :one
INSERT INTO vendor_licenses (
	price_paid_pico, user_id
) VALUES (
	$1, $2
) RETURNING id, price_paid_pico, user_id, created_at
`

type CreateVendorLicenseParams struct {
	PricePaidPico int64
	UserID        uuid.UUID
}

func (q *Queries) CreateVendorLicense(ctx context.Context, arg CreateVendorLicenseParams) (VendorLicense, error) {
	row := q.db.QueryRow(ctx, createVendorLicense, arg.PricePaidPico, arg.UserID)
	var i VendorLicense
	err := row.Scan(
		&i.ID,
		&i.PricePaidPico,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getNumberOfVendorLicenses = `-- name: GetNumberOfVendorLicenses :one
SELECT COUNT(*) FROM vendor_licenses
`

func (q *Queries) GetNumberOfVendorLicenses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNumberOfVendorLicenses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTermsOfServiceForVendor = `-- name: GetTermsOfServiceForVendor :one
SELECT id, content, vendor_id, created_at 
FROM terms_of_services 
WHERE vendor_id = $1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetTermsOfServiceForVendor(ctx context.Context, vendorID uuid.UUID) (TermsOfService, error) {
	row := q.db.QueryRow(ctx, getTermsOfServiceForVendor, vendorID)
	var i TermsOfService
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.VendorID,
		&i.CreatedAt,
	)
	return i, err
}

const getVendorLicenseForUser = `-- name: GetVendorLicenseForUser :one
SELECT id, price_paid_pico, user_id, created_at FROM vendor_licenses
WHERE user_id = $1
`

func (q *Queries) GetVendorLicenseForUser(ctx context.Context, userID uuid.UUID) (VendorLicense, error) {
	row := q.db.QueryRow(ctx, getVendorLicenseForUser, userID)
	var i VendorLicense
	err := row.Scan(
		&i.ID,
		&i.PricePaidPico,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const hasVendorLicense = `-- name: HasVendorLicense :one
SELECT 1
FROM vendor_licenses
WHERE user_id = $1
`

func (q *Queries) HasVendorLicense(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, hasVendorLicense, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
