// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendor_application.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createVendorApplication = `-- name: CreateVendorApplication :one
INSERT INTO vendor_applications (
	existing_vendor, letter, price_paid_pico, user_id
) VALUES (
	$1, $2, $3, $4
) RETURNING id, existing_vendor, letter, price_paid_pico, user_id, created_at
`

type CreateVendorApplicationParams struct {
	ExistingVendor bool
	Letter         string
	PricePaidPico  int64
	UserID         uuid.UUID
}

func (q *Queries) CreateVendorApplication(ctx context.Context, arg CreateVendorApplicationParams) (VendorApplication, error) {
	row := q.db.QueryRow(ctx, createVendorApplication,
		arg.ExistingVendor,
		arg.Letter,
		arg.PricePaidPico,
		arg.UserID,
	)
	var i VendorApplication
	err := row.Scan(
		&i.ID,
		&i.ExistingVendor,
		&i.Letter,
		&i.PricePaidPico,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVendorApplication = `-- name: DeleteVendorApplication :exec
DELETE FROM vendor_applications WHERE id = $1
`

func (q *Queries) DeleteVendorApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVendorApplication, id)
	return err
}

const getVendorApplication = `-- name: GetVendorApplication :one
SELECT id, existing_vendor, letter, price_paid_pico, user_id, created_at FROM vendor_applications
WHERE id = $1
`

func (q *Queries) GetVendorApplication(ctx context.Context, id uuid.UUID) (VendorApplication, error) {
	row := q.db.QueryRow(ctx, getVendorApplication, id)
	var i VendorApplication
	err := row.Scan(
		&i.ID,
		&i.ExistingVendor,
		&i.Letter,
		&i.PricePaidPico,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getVendorApplications = `-- name: GetVendorApplications :many
SELECT id, existing_vendor, letter, price_paid_pico, user_id, created_at FROM vendor_applications
`

func (q *Queries) GetVendorApplications(ctx context.Context) ([]VendorApplication, error) {
	rows, err := q.db.Query(ctx, getVendorApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorApplication
	for rows.Next() {
		var i VendorApplication
		if err := rows.Scan(
			&i.ID,
			&i.ExistingVendor,
			&i.Letter,
			&i.PricePaidPico,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
