// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const addWalletBalance = `-- name: AddWalletBalance :one
UPDATE wallets
SET balance_pico = balance_pico + $2
WHERE id = $1 AND $2::numeric >= 0
RETURNING id, balance_pico, user_id
`

type AddWalletBalanceParams struct {
	ID     uuid.UUID
	Amount decimal.Decimal
}

func (q *Queries) AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, addWalletBalance, arg.ID, arg.Amount)
	var i Wallet
	err := row.Scan(&i.ID, &i.BalancePico, &i.UserID)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
	user_id
) VALUES(
	$1
) RETURNING id, balance_pico, user_id
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(&i.ID, &i.BalancePico, &i.UserID)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, balance_pico, user_id FROM wallets
WHERE id = $1
`

func (q *Queries) GetWallet(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(&i.ID, &i.BalancePico, &i.UserID)
	return i, err
}

const getWalletForUser = `-- name: GetWalletForUser :one
SELECT wallets.id, wallets.balance_pico, wallets.user_id 
FROM wallets
JOIN users ON users.id = wallets.user_id
WHERE users.id = $1
`

func (q *Queries) GetWalletForUser(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletForUser, id)
	var i Wallet
	err := row.Scan(&i.ID, &i.BalancePico, &i.UserID)
	return i, err
}

const getWallets = `-- name: GetWallets :many
SELECT id, balance_pico, user_id FROM wallets
`

func (q *Queries) GetWallets(ctx context.Context) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, getWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(&i.ID, &i.BalancePico, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduceWalletBalance = `-- name: ReduceWalletBalance :one
UPDATE wallets
SET balance_pico = balance_pico - $2::numeric
WHERE id = $1 AND balance_pico >= $2::numeric AND $2::numeric >= 0
RETURNING id, balance_pico, user_id
`

type ReduceWalletBalanceParams struct {
	ID     uuid.UUID
	Amount decimal.Decimal
}

func (q *Queries) ReduceWalletBalance(ctx context.Context, arg ReduceWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, reduceWalletBalance, arg.ID, arg.Amount)
	var i Wallet
	err := row.Scan(&i.ID, &i.BalancePico, &i.UserID)
	return i, err
}
