// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: withdrawal.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO withdrawals (
	amount_pico, destination_address, status
) VALUES(
	$1, $2, $3
) RETURNING id, amount_pico, destination_address, status, created_at
`

type CreateWithdrawalParams struct {
	AmountPico         decimal.Decimal
	DestinationAddress string
	Status             WithdrawalStatus
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, createWithdrawal, arg.AmountPico, arg.DestinationAddress, arg.Status)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.AmountPico,
		&i.DestinationAddress,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWithdrawal = `-- name: DeleteWithdrawal :exec
DELETE FROM withdrawals
WHERE id = $1
`

func (q *Queries) DeleteWithdrawal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWithdrawal, id)
	return err
}

const getWithdrawalsWithStatus = `-- name: GetWithdrawalsWithStatus :many
SELECT id, amount_pico, destination_address, status, created_at FROM withdrawals
WHERE status = $1
`

func (q *Queries) GetWithdrawalsWithStatus(ctx context.Context, status WithdrawalStatus) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, getWithdrawalsWithStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Withdrawal
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.AmountPico,
			&i.DestinationAddress,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWithdrawalStatus = `-- name: UpdateWithdrawalStatus :one
UPDATE withdrawals
SET status = $2
WHERE id = $1
RETURNING id, amount_pico, destination_address, status, created_at
`

type UpdateWithdrawalStatusParams struct {
	ID     uuid.UUID
	Status WithdrawalStatus
}

func (q *Queries) UpdateWithdrawalStatus(ctx context.Context, arg UpdateWithdrawalStatusParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, updateWithdrawalStatus, arg.ID, arg.Status)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.AmountPico,
		&i.DestinationAddress,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
