// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: xmr_prices.sql

package repo

import (
	"context"
)

const getXMRPrices = `-- name: GetXMRPrices :one
SELECT id, data, updated_at FROM xmr_prices WHERE id = 1
`

func (q *Queries) GetXMRPrices(ctx context.Context) (XmrPrice, error) {
	row := q.db.QueryRow(ctx, getXMRPrices)
	var i XmrPrice
	err := row.Scan(&i.ID, &i.Data, &i.UpdatedAt)
	return i, err
}

const updateXMRPrices = `-- name: UpdateXMRPrices :exec
INSERT INTO xmr_prices (id, data)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE
SET data = EXCLUDED.data, 
	updated_at = NOW()
`

func (q *Queries) UpdateXMRPrices(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, updateXMRPrices, data)
	return err
}
