FROM golang:1.24.4 AS builder

WORKDIR /build

COPY go.mod go.sum ./ 

RUN go mod tidy
RUN go mod download && go mod verify

COPY . .

ENV CGO_ENABLED=1 GOOS=linux
RUN go build \
	-tags timetzdata \
	-ldflags="-w -s" \
	-trimpath \
	-o admin \
	./cmd/admin

FROM gcr.io/distroless/base-debian13:nonroot
WORKDIR /app

COPY --chown=nonroot:nonroot static/ static/
COPY --chown=nonroot:nonroot ui/ ui/ 
COPY --from=builder --chown=nonroot:nonroot /build/admin .

EXPOSE 4002
ENTRYPOINT ["./admin"]
